name = "blog"

kv_namespaces = [
  { binding = "SUBSCRIBERS" }
]

[build]
command = "npm run build:esbuild"
watch_dir = "./dist"

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"

[miniflare]
upstream = "http://localhost:5000"
kv_persist = true
