name = "blog"
main = "./dist/worker.mjs"
workers_dev = false
compatibility_date = "2022-05-20"

kv_namespaces = [
  { binding = "SUBSCRIBERS", id="29bb0a582e6d49089775f462ba395859" }
]

[build]
command = "npm run build:esbuild"
watch_dir = "./dist"

[miniflare]
upstream = "http://localhost:5000"
kv_persist = true
