name = "blog"
compatibility_date = "2024-07-01"

[[r2_buckets]]
binding = "BUCKET"
preview_bucket_name = "blog"
bucket_name = "blog"

[[r2_buckets]]
binding = "STRAVA"
preview_bucket_name = "strava"
bucket_name = "strava"

[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "2862cc61-ed37-4c73-a74b-b5cb009b76b7"