name = "blog"

[[r2_buckets]]
binding = "BUCKET"
preview_bucket_name = "blog"
bucket_name = "blog"

[[r2_buckets]]
binding = "STRAVA"
preview_bucket_name = "strava"
bucket_name = "strava"

[[d1_database]]
binding = "DB"
database_name = "blog"
database_id = "59d1cf85-8fac-4a48-9f52-cb97dbae8561"