name = "blog"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat_v2" ]

[[r2_buckets]]
binding = "BLOG"
preview_bucket_name = "blog"
bucket_name = "blog"

[[r2_buckets]]
binding = "STRAVA"
preview_bucket_name = "strava"
bucket_name = "strava"

[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "690af449-57fa-41ac-9adf-e4e7ababf788"