name: Run migrations
on:
  push:
    paths:
      - .github/workflows/run-migrations.yaml
      - migrations/**
      - src/schemas/**
      - drizzle.config.ts
      - package.json
      - wrangler.toml
concurrency: migrations
jobs:
  node:
    name: Run migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: d1 migrations apply blog --remote
          wranglerVersion: "4.15.2"